version: '3.9'

services:
  database_insta_api:
    image: postgres
    container_name: boilerplate
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=boilerplate
      - POSTGRES_PASSWORD=boilerplate
      - POSTGRES_DB=boilerplate
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local